### Retrieve all vehicles
GET http://localhost:3000/vehicles

### Retrieve a vehicle by id
GET http://localhost:3000/vehicles/af3d17f2-fe5c-4b08-93e2-a827e1cde292

### Create a vehicle
POST http://localhost:3000/vehicles
Content-Type: application/json

{
      "brand": "Nissan",
      "model": "Leaf",
      "year": 2019,
      "price": 29999,
      "range_km": 270,
      "color": "White",
      "condition": "New",
      "battery_capacity_kwh": 40,
      "charging_speed_kw": 50,
      "seats": 5,
      "drivetrain": "FWD",
      "location": "München",
      "autopilot": false,
      "kilometer_count": 0,
      "accidents": false
    }

### Update a vehicle
PUT http://localhost:3000/vehicles/3a031a0f-4d52-4248-a597-c822f29cd1f7
Content-Type: application/json

{
    "brand": "Nissan",
    "model": "Leaf",
    "year": 2019,
    "price": 29999,
    "range_km": 270,
    "color": "White",
    "condition": "New",
    "battery_capacity_kwh": 40,
    "charging_speed_kw": 50,
    "seats": 5,
    "drivetrain": "FWD",
    "location": "München",
    "autopilot": false,
    "kilometer_count": 0,
    "accidents": false
}

### Delete a vehicle
DELETE http://localhost:3000/vehicles/3a031a0f-4d52-4248-a597-c822f29cd1f7